#!/bin/bash
if [ "adbd cannot run as root in production builds" != "$(adb root)" ]
then
    name=$1
    if [ ${#name} == "0" ]
    then
        echo "Please print packagename:"
        read name
    fi
    result=$(adb shell ps -ef |grep -i "$name")
    oldifs="$IFS"
    IFS=$'\n'
    arr=($result)

    if [ ${#arr} == "0" ]
    then
        echo "Process not found."
    else
        i=0
        for file in ${arr[@]}
        do
            i=`expr $i + 1`;
            echo "NO.$i        Packagename:  $(echo $file | awk '{print $8}')" |grep  $name
        done 
        IFS="$oldifs"
        echo ""
        echo "Got  ${#arr[@]} processes."
        echo ""
        if [ ${#arr[@]} -ge 1 ]
        then
            echo "Which process do you want to kill? (print number):"
            read number
            read -a WORDS <<< $number
            for i in ${WORDS[@]}
            do
                num=`expr $i - 1`; 
                if [ $num -ge 0 ]
                then
                    id="${arr[$num]:13:5}"
                    adb shell kill "$id"
                fi
            done 
        fi
    fi
else
    echo "adbd cannot run as root in production builds"
fi

