#!/bin/bash
name=$1
adb root
if [ ${#name} == "0" ]
then
    echo "Print app name"
    read name
fi
result=$(adb shell ps -ef |grep -i "$name")
oldifs="$IFS"
IFS=$'\n'
arr=($result)

if [ ${#arr} == "0" ]
then
    echo "app not found"
else
    i=0
    for file in ${arr[@]}
    do
        i=`expr $i + 1`;
        echo "count:$i        result: ${file}"
    done 
    IFS="$oldifs"
    echo ""
    echo "There are ${#arr[@]} results."
    if [ ${#arr[@]} -ge 1 ]
    then
        echo "Please print the count number."
        read count
        num=`expr $count - 1`; 
    fi
    if [ $num -ge 0 ]
    then
    
        id="${arr[$num]:13:5}"
        adb shell kill "$id"
    fi
fi
